version: '3'

services:
  node-app:
    build:
      context: ./node-app
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./node-app:/app
    environment:
      - PLC_HOST=host.docker.internal
      - PLC_PORT=502

  web-panel:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html