services:
  node-app:
    build:
      context: ./node-app
    ports:
      - "3000:3000"
    volumes:
      - ./node-app:/app
    depends_on:
      - python-app

  python-app:
    build:
      context: ./python-app
    ports:
      - "502:502"
      - "5901:5901"
      - "6080:6080"
    volumes:
      - ./python-app:/app

  web-panel:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge